/**
 * Supplied class Part.java
 */

/**
 *
 * @author Joshua Corpuz
 */
package model;

import javafx.beans.property.SimpleStringProperty;

/**
 * This creates the Part class.
 * The part class is an abstract class.
 */
public abstract class Part {

    private int id;
    private SimpleStringProperty partName;
    private int partInventoryLevel, maxInventory, minInventory;
    private double price;

    //id field needs to also have a corresponding static int id to keep count of all the inputted items.
    private static int partCounter = 1;

    /**
     * This is the constructor that initializes the data fields within a Part object.
     * Note: The part's ID number is autogenerated
     * @param partName The part's name.
     * @param partInventoryLevel The part's stock level
     * @param price The part's price.
     * @param maxInventory The part's maximum inventory level
     * @param minInventory The part's minimum inventory level
     */
    public Part(String partName, int partInventoryLevel, double price, int maxInventory, int minInventory) {
        setId();
        setPartName(partName);
        setPartInventoryLevel(partInventoryLevel);
        setPrice(price);
        setMaxInventory(maxInventory);
        setMinInventory(minInventory);
    }

    /**
     * Method that returns the part's ID variable.
     * @return This returns the ID number as an integer
     */
    public int getId() {
        return id;
    }

    /**
     * This method sets the id for an Object. It utilizes an static variable as a counter to auto generate an ID number
     */
    public void setId() {
        this.id = partCounter++;
    }

    /**
     * This method returns a Part object's name
     * @return returns the Part's name as a string
     */
    public String getPartName() {
        return partName.get();
    }

    /**
     * This method sets the Part object's name.
     * @param partName A String object is passed as an argument.
     */
    public void setPartName(String partName) {
        this.partName = new SimpleStringProperty(partName);
    }

    public int getPartInventoryLevel() {
        return partInventoryLevel;
    }

    public void setPartInventoryLevel(int partInventoryLevel) {
        this.partInventoryLevel = partInventoryLevel;
    }

    public int getMaxInventory() {
        return maxInventory;
    }

    public void setMaxInventory(int maxInventory) {
        this.maxInventory = maxInventory;
    }

    public int getMinInventory() {
        return minInventory;
    }

    public void setMinInventory(int minInventory) {
        this.minInventory = minInventory;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

}
